### ISSUE TITLE
Publish some SciSpark notebook examples using SciTensor and the MCCs

### ISSUE THREAD

**Issue by chrismattmann** [SciSpark/SciSpark#10]
Having a reproducible set of notebooks that actually call the SciTensor code for MCC.

**Comment by ghost** [comment]
looking (a little) into [Apache Zeppelin](https://zeppelin.incubator.apache.org)

**Comment by chrismattmann** [comment]
yeah we have it deployed at http://scispark.jpl.nasa.gov:8080/#/ but it's behind VPN right now - we are working to open it up.

**Comment by kwhitehall** [comment]
Hey @chrismattmann this issue is addressed in PR #36

**Comment by kwhitehall** [comment]
SciSpark notebooks demonstrating this functionality can also be found at https://github.com/SciSpark/scispark_zeppelin_notebooks These are the notebooks used in the ESIP workshop.

**Comment by kwhitehall** [comment]
Hey @chrismattmann, I reopened this issue because the API is changing and the codes in the notebooks will be broken. Can we make a ESIP release for commits up to Jul 14, 2016 (inclusive)?

**Comment by rahulpalamuttam** [comment]
@chrismattmann @kwhitehall @BrianWilson1 

I'm going to cleanup some of the branches we have.
I'm going to leave branch-0.1 and branch-0.2
The rest can be deleted.

I am also going to add a branch titled branch-ESIP-Release.
We'll work on that branch to make sure SciSpark is working for the people who want to try it out frm ESIP.

Also for the notebook, we use the gesdisc dataset, which now requires credentials.
Let's make sure that we set credentials in the notebooks (if we have to).

**Comment by rahulpalamuttam** [comment]
Actually i'm going to name it branch-0.3-ESIP.

**Comment by kwhitehall** [comment]
Thanks @rahulpalamuttam. 
Update the readme on the scispark notebook repo accordingly. See https://github.com/SciSpark/scispark_zeppelin_notebooks/pull/11
