### ISSUE TITLE
New split functions SciSparkContext

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#108]
Lets have two split functions as brian suggested.
1. sc.sciDatasets(path : String, vars : List[String], partitionCount : Int)
   This is to handle the simple case of many small files split across a dimension (time)
   We should make this a general function, that parses the path name to load from different urls (opendap, hdfs, localfs). Once the distinction has made, then delegate to the pre-existing functions in SciSparkContext.
2. sc.sciDataset(path : String, vars : List[String], partitionCount : Int, splitAlgorithm : howitssplit) 
   --> note that the name is not plural
   This is to handle the case of one large file. We will naively split it by row first (or just along the first dimension).

**Comment by kwhitehall** [comment]
This is addressed in PR#177.
