### ISSUE TITLE
Second SciSpark paper

### ISSUE THREAD

**Issue by chrismattmann** [SciSpark/SciSpark#11]
Expand upon IEEE Big Data paper and write another SciSpark paper

**Comment by rahulpalamuttam** [comment]
Looks like we're shooting for [IEEE Big Data 2016](http://cci.drexel.edu/bigdata/bigdata2016/index.html).
@BrianWilson1 mentioned he would have an outline towards this later this week.

We were looking at the workshop here (the same one from last year really) [Big Data Challenges, Research, and Technologies in the Earth and Planetary Sciences](http://geo-bigdata.github.io/).
The due date is September 26.

Perhaps also considering the workshop on [Big Spatial Data](http://cse.ucdenver.edu/~BSD2016/).
The due date is October 5.

**Comment by rahulpalamuttam** [comment]
Closing this.
