### ISSUE TITLE
MCC time series pairing bug

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#115]
We take the date value from the file name, and convert it to an int.
We then use this key to organize pairs like so:

(p, p+1), (p + 1, p + 2), (p + 2, p + 3)

However, the date values don't increment like normal numbers. They increment according to hours in a day.

Take a look at how the date values increment :

/resources/1gb/merg_2006080800_4km-pixel.nc
-rw-r--r--   3 sdeploy supergroup   20470812 2016-08-09 19:43 /resources/1gb/merg_2006080801_4km-pixel.nc
-rw-r--r--   3 sdeploy supergroup   20470812 2016-08-09 19:43 /resources/1gb/merg_2006080802_4km-pixel.nc
-rw-r--r--   3 sdeploy supergroup   20470812 2016-08-09 19:43 
...
...
-rw-r--r--   3 sdeploy supergroup   20470812 2016-08-09 19:43 /resources/1gb/merg_2006080822_4km-pixel.nc
-rw-r--r--   3 sdeploy supergroup   20470812 2016-08-09 19:43 /resources/1gb/merg_2006080823_4km-pixel.nc
-rw-r--r--   3 sdeploy supergroup   20470812 2016-08-09 19:43 /resources/1gb/merg_2006080900_4km-pixel.nc

From 2006080823 to 2006080900

Right now we throw out any of the following types of pairs
(_23, _0)

The solution would be to
1. sort it by the date value
2. Then use zipWithIndex 

This gets us the proper timeseries indices associated with each sciTensor so we can pair them properly.

**Comment by kwhitehall** [comment]
Ok. sounds good.

**Comment by kwhitehall** [comment]
This is address in PR #124
