### ISSUE TITLE
Remove unnecessary files in org.dia.algorithms.mcc

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#122]
There are old mcc algorithm codes in org.dia.algorithms.mcc.
The one's that should be preserved are are the ones that we use regularly in our notebooks.

**Comment by rahulpalamuttam** [comment]
The above PR is closed because I deleted the branch.
Let's talk about what actually should be done to these files.
Just want a bit more clarity before deleting code.

I intended to only keep the following files in org.dia.algorithms.mcc :

MainDistGraphMCC.scala
MainNetcdfDFSMCC.scala
MCCEdge.scala
MCCNode.scala
MCCOps.scala
NtcdfDFSMCC.scala

Let me know if that is okay.

**Comment by kwhitehall** [comment]
@rahulpalamuttam this is fine by me. @sujen1412 is this clean up ok with you?

**Comment by sujen1412** [comment]
@rahulpalamuttam @kwhitehall yes fine with me.

**Comment by kwhitehall** [comment]
Addressed with PR #125.
