### ISSUE TITLE
ND4j throws ArrayIndexOutOfBounds Exceptions

### ISSUE THREAD

**Issue by sujen1412** [SciSpark/SciSpark#127]

**Comment by sujen1412** [comment]
@rahulpalamuttam : please see this issue.

**Comment by rahulpalamuttam** [comment]
@sujen1412 @kwhitehall 

Sujen and I explored the issue together.

Here is the breaking scenario :
When we want to read in a single dimension array i.e. "lat" or "lon".
The shape of the array has size 1. 
However, Nd4j only accepts shapes with sizes >= 2.
They treat single dimension arrays as arrays of shape (1, sizeOfDimension)

When instantiating these arrays, we need to check if the array is only of one dimension.
If it is, then prepend a 1 to the shape array.

**Comment by rahulpalamuttam** [comment]
@sujen - can this issue be closed now?

**Comment by sujen1412** [comment]
Yup
