### ISSUE TITLE
Training session at ESIP Summer 2016

### ISSUE THREAD

**Issue by chrismattmann** [SciSpark/SciSpark#13]
Have a SciSpark training session at ESIP Summer 2016

**Comment by rahulpalamuttam** [comment]
This issue loos like it can be closed :)
It was a success!

@chrismattmann @BrianWilson1 @kwhitehall 
Do you have anymore actionable items towards this?

**Comment by kwhitehall** [comment]
I agree @rahulpalamuttam. @chrismattmann @BrianWilson1  @wmburke any objections to closing?

**Comment by rahulpalamuttam** [comment]
@kwhitehall 
So can we close this?

**Comment by kwhitehall** [comment]
Let's hold a little longer for others to participate. Will close within 24hrs if no response.

**Comment by kwhitehall** [comment]
@chrismattmann @rahulpalamuttam @wmburke @BrianWilson1 @MBoustani @valeriearoth @pymonger +agoodm
