### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#130]
Delete Update section - it doesn't make sense to have it anymore.

Move the following sections to their own wikipages and have links to them under each section.
Installation
Getting Started
Running Tests
GTG

Get rid of technology section or just have it in it's own wiki page.

Thank you @lewismc for pointing this out!

@kwhitehall @BrianWilson1 @chrismattmann thoughts?

**Comment by kwhitehall** [comment]
LGTM @rahulpalamuttam. Much more manageable to the end user.
Issue addressed in PR #132 .
