### ISSUE TITLE
Avoid using LinkedHashMap's with Kryo

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#138]
LinkedHashMap has serialization issues with Kryo.
For a description of the problem please visit the following spark email thread I started:
http://apache-spark-developers-list.1001551.n3.nabble.com/Serialization-troubles-with-mutable-LinkedHashMap-td18693.html

I'm still waiting for a reply about whether it's a known issue or not.
Otherwise I think it's a safe bet to file a JIRA.

The following user on stack-overflow has the same issue:
http://stackoverflow.com/questions/37869812/serailize-linked-hash-map-kryo

I had a chat on the kryo gitter page about the issue as well.
There's a subsequent issue that's been filed on it:
https://github.com/EsotericSoftware/kryo/issues/452

Seems to be that a few of the standard scala collection classes do not have corresponding serializers.

@kwhitehall @BrianWilson1

**Comment by kwhitehall** [comment]
Thanks for documenting the issue as well @rahulpalamuttam .
This has been addressed in PR #139
