### ISSUE TITLE
Create an Apps dir to demo SciSpark applications 

### ISSUE THREAD

**Issue by sujen1412** [SciSpark/SciSpark#142]
We should have an apps directory to demo the different SciSpark applications implemented, MCC and PDFClustering for now. These would act as guides to a user who can then develop his own applications, which may include extending an algorithm already in SciSpark or implementing one of his own. 

EDIT: 
Linking the conversation here :
https://gist.github.com/rahulpalamuttam/47de443df05a4d357c56aaa5afd8a679

**Comment by kwhitehall** [comment]
This has been address in PR #193
