### ISSUE TITLE
Update GTGRunner to generate netcdf files

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#151]

**Comment by rahulpalamuttam** [comment]
@kwhitehall 
I have code in another branch that generates random multivariable Netcdf files.
Is that what you had in mind?

EDIT:
Never mind, I realized that you actually wanted the component/node data that was gleaned after a run of GTGRunner.

**Comment by kwhitehall** [comment]
Ack'ed.

**Comment by kwhitehall** [comment]
This issue has been addressed in PR #150.
EDIT: Partially addressed.

**Comment by kwhitehall** [comment]
Opps! Didn't mean to close this! Reopening..

**Comment by kwhitehall** [comment]
This issue has been addressed in PR #155
