### ISSUE TITLE
How to contribute wiki page

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#152]
I was thinking of adding a how to contribute page in our wiki, and add a corresponding section to the README.

Here's a structure for the page I was thinking of :
1. Fork the repo to your own github repo
2. Install Intellij and use it to pull the project from the repo
   - this section would detail proper installation and setup with intellij with some pictures
3. Guidelines for submitting a pull request
   - how to use  sbt plugins (scalastyle, scalatest etc.) to make sure the fix will be accepted by travis ci

I realize that we use a variety of tools on the team i.e. intellij, eclipse, sublime, etc.
The page could be a nice reference for people looking to get more involved.

**Comment by kwhitehall** [comment]
I like this idea @rahulpalamuttam
Some suggestions on my part.
- Intellij is not a requirement but more of a suggestion. This should be in a link to a separate wiki. Like wise a page can be written for how to set up eclipse, sublime, etc.

Expounding on the guidelines:
1. fork repo
1a. update current repo
2. make branch with issue number
3. Guidelines for submitting include:
- issue tracking rules - 
- code readability rules - scala checker, (should we get a pylint file too?)
- steps to submit a PR - include tense to use, etc.
- Addressing code review

**Comment by jfraj** [comment]
I would add my +1 to encourage the implementation of this.  Our group is interested in exploring (and potentially contributing) to scispark.  If the wiki gets updated as suggested by this issue, that would be a great incentive!  Looking forward to seeing this implemented.

**Comment by kwhitehall** [comment]
Hi @jfraj I'll get to this shortly. Will ping here when it is up.

**Comment by kwhitehall** [comment]
This has been addressed on the [Wiki pages](https://github.com/SciSpark/SciSpark/wiki/Becoming-a-SciSpark-contributor). Please feel free to make updates and suggestions for improvement.

**Comment by kwhitehall** [comment]
Closing this issue as page has been added.
