### ISSUE TITLE
Clean up MCCOps to remove unused functions

### ISSUE THREAD

**Issue by sujen1412** [SciSpark/SciSpark#164]
EDIT by @rahulpalamuttam:
- [ ]  Move reduceResolution and reduceRectangleResolution implementations to AbstractTensor
- [ ]  Remove findCloudComponents and findConnectedComponents in MCCOps
- [ ] Remove computeBasicStats
- [ ] remove findCloudElements, checkCriteria and checkComponents Overlap
- [ ] Move LabelConnectedComponents to tensor class and rename to LabelComponents

**Comment by kwhitehall** [comment]
Addressed in PR #170
