### ISSUE TITLE
Port GTG runner functions to MCCOps

### ISSUE THREAD

**Issue by sujen1412** [SciSpark/SciSpark#165]
There are a few functions performing MCC operations, they should be moved to MCCOps. 

EDIT by @rahulpalamuttam:
- [ ]  Move pairConsecutiveFrames to SRDDFunctions. Include parameter to specify the attribute to key by for the sort operation
- [ ]  Refactor the huge lambda expression in GTGRunner.findEdges() to separate functions and move them over to MCCOps

**Comment by kwhitehall** [comment]
Looks reasonable.

**Comment by kwhitehall** [comment]
These are addressed in PR #179
