### ISSUE TITLE
Add indentation checker to scalastyle checker.

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#167]
Currently, the scalastyle checker does not check the code indentation level.
Here is the configuration code to be added to scalastyle-config.xml

http://www.scalastyle.org/rules-dev.html#org_scalastyle_file_IndentationChecker

Note that the default multiline function parameter indent level is 4.
The function parameter indent is probably going to affect nearly all the multiline function signatures.

A PR addressing this issue will :
1. Add the xml parameter
2. Make changes to the code base so that it meets the indentation style requirements.
- The PR will most likely affect code in many .scala files in the project.

The indent spacing of 2 and parameter indent spacing of 4 is specified in databricks' scalastyle guide. https://github.com/databricks/scala-style-guide#spacing-and-indentation.

**Comment by kwhitehall** [comment]
This is addressed in PR #168
