### ISSUE TITLE
update OpenDap links

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#169]
GESDISC update their OPeNDAP server to for TRMM data from http://disc2.gesdisc.eosdis.nasa.gov/opendap/hyrax/TRMM_L3/
to 
http://disc2.gesdisc.eosdis.nasa.gov/opendap/TRMM_L3/
Updates need to be made accordingly in our code.

**Comment by kwhitehall** [comment]
It appears these URLs are one in the same.

**Comment by rahulpalamuttam** [comment]
@kwhitehall 
Can this issue be closed?

**Comment by kwhitehall** [comment]
URL still working fine. Closing this issue. Labelling as invalid.
