### ISSUE TITLE
NetcdfFile.getName is deprecated => resolve it

### ISSUE THREAD

**Issue by ghost** [SciSpark/SciSpark#17]
see:
https://www.unidata.ucar.edu/software/thredds/v4.3/netcdf-java/v4.3/javadoc/ucar/nc2/CDMNode.html#getShortName()

use getShort/FullName instead, whichever's the right one
(didnt want to break something by making a quick choice without fully knowing the relevant code at this point)

**Comment by chrismattmann** [comment]
I think it would be fine to update this - we can just do a quick grep in the code to see if it's used anywhere else. PRs welcome on this @legendOfZelda

**Comment by ghost** [comment]
ok. its not used actually. i just chose getShortName because thats what we will be using i think. if not i can still check at a later point. PR to follow soon. @chrismattmann

**Comment by chrismattmann** [comment]
thanks @legendOfZelda see my comments on #18

**Comment by chrismattmann** [comment]
closing per comments
