### ISSUE TITLE
update the notebooks folder in the main SciSpark repo

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#184]
The Scispark notebooks in here should contain the notebooks associated with the basic SciSpark API e.g. using sciDataset, PDF clustering, the MCS usecase that works with the new code. Thoughts?

**Comment by rahulpalamuttam** [comment]
I am +1 for having these notebook's associated with the aforementioned API.

However, I am not sure why we are keeping the notebooks in the main SciSpark repo.
I understand that SciSpark is a project that incorporates many components and technologies.
However, the notebook JSON's should be in another repository all together i.e. this repository : https://github.com/SciSpark/scispark_zeppelin_notebooks

If we want to have code examples of using sciDataset, PDF clustering, MCS then there should be .scala files that demonstrate those examples under an examples directory in the SciSpark repo.

There should just be one notebook repository for all the notebooks we demonstrate and for users to play with.

@kwhitehall @BrianWilson1 @chrismattmann what do you think?

**Comment by kwhitehall** [comment]
Agreed @rahulpalamuttam. 
The actions here on this issue then should be:
- [x] remove notebooks folder from SciSpark repo
- [x] add documentation on SciSpark repo to link the SciSpark zeppelin notebooks 

On the scispark_zeppelin_notebooks repo
- [x] move the current notebooks to branch called ESIP workshop
- [x] update the relevant notebooks to represent the new API stored in subfolders such as /images, /tutorials and /usecases
- [x] update readme.

**Comment by kwhitehall** [comment]
Addressed in PR #197.
Readme updated directly on GH. 
Updates made to the repo in [issue 12](https://github.com/SciSpark/scispark_zeppelin_notebooks/issues/12)
Updated Readme on that repo directly.
