### ISSUE TITLE
Main... classes in org.dia.algorithms.mcc share lots of code => abstract out

### ISSUE THREAD

**Issue by ghost** [SciSpark/SciSpark#21]
the Main... classes in org.dia.algorithms.mcc share a lot of identical / similar code:
- setting up cmd line args, scisparkcontext
- data source for initial SRDD (random matrices / files / URIs) => abstract out
- groupBy / cartesian to pair consecutive frames => abstract out or only choose groupBy because more efficient anyway
- approach to get edges for a fixed pair of consecutive scitensors: cartesian / in-place iteration => abstract out
- collecting the edges at the driver + postprocessing (e.g. writing to json)

**Comment by chrismattmann** [comment]
+1

**Comment by rahulpalamuttam** [comment]
@legendOfZelda 
Are you working on this currently? 
I wanted to tackle this + finish the iterative depth first search implementation of the mcc search algorithm. (Will open a separate issue for that).

**Comment by ghost** [comment]
no, im working on the pdfclustering algorithm. i let you handle this here.

**Comment by kwhitehall** [comment]
This issue has been addressed in PR #121 #125 #133 #137
