### ISSUE TITLE
abstract out checkCriteria to allow different criteria for clouds

### ISSUE THREAD

**Issue by ghost** [SciSpark/SciSpark#22]
right now there's only 1 hardcoded cloud criteria:
(area >= 40.0) || (area < 40.0) && ((dMax - dMin) > 10.0)

allow for other criterias.

**Comment by kwhitehall** [comment]
This has been addressed in MCC refactoring PRs.

**Comment by kwhitehall** [comment]
Closing this issue as addressed in MCS refactoring PRs to include PR #174.
