### ISSUE TITLE
Investigate Constants.scala line 28

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#27]
I am not certain if this variable is needed in the general code. I breaks some of the test. @legendOfZelda this may be related to your issue. @rahulpalamuttam @renato2099 any thoughts on this?

**Comment by rahulpalamuttam** [comment]
Hi Kim,

I ran into issues with this line when importing classes in the spark-shell.
I think it may have to do with how scala 2.11 deals with the '->' operator.

I do not think the variable is necessary. 
We can either delete the line or replace the '->' operator and make the pairs into tuples like so
val DATASET_VARS = collection.immutable.HashMap(("TRMM_L3", "compData"), ("ncml", "TotCldLiqH2O_A"))

**Comment by kwhitehall** [comment]
Thanks @rahulpalamuttam I've looked around and couldn't find use for the variable myself. I think it best we just remove it from the file.
