### ISSUE TITLE
nd4j: Could not find the selected project in the reactor

### ISSUE THREAD

**Issue by valeriearoth** [SciSpark/SciSpark#39]
I believe I'm missing a step in trying to install nd4j.

So far I've cloned the nd4j files from GitHub and then added the dependency listed on the nd4j GitHub page to the POM file. I've also set the corresponding version in the properties section. Everything seemed to compile fine, but when I try to run the tests, files such as nd4j-java and nd4j-x86 aren't being found.

One example of a test I'm running is

```
mvn test -pl nd4j-java
```

and this is the error I get is

```
Could not find the selected project in the reactor: nd4j-java
```

Any help or suggestions of what I could try would be greatly appreciated.

**Comment by sujen1412** [comment]
Hi @valeriearoth, 
What is the task you are trying to achieve that requires building/installing nd4j ?

**Comment by valeriearoth** [comment]
Hi Sujen. I'm trying to install and document SciSpark and it was one of the requirements. Do I not need it?

**Comment by sujen1412** [comment]
@valeriearoth, no you don't. Follow these : 
1. Install Scala: 2.10.x (http://www.scala-lang.org/download/) Be sure to add scala/bin folder to your environment. 
2. Install Spark 1.6.0 with Scala 2.10 dependency. NB: To do so you must build the Spark installation. Download the SciSpark source file at http://spark.apache.org/downloads.html and follow the directions for builidng with Scala 2.11 http://spark.apache.org/docs/latest/building-spark.html#building-for-scala-211
3. Add the installation folder to your environment SPARK_HOME = /path/to/installation
4. Download the latest version of SciSpark from https://github.com/SciSpark/SciSpark
5. Maven 2.0x+ https://maven.apache.org/download.cgi Be sure to add Maven on your environment. 
6. SBT: v0.13.5+ http://www.scala-sbt.org/download.html 
7. Run sbt clean assembly

If these above steps work, we will update the README on this repo. 

Thanks!

**Comment by valeriearoth** [comment]
@sujen1412 Cool, I've done all of these things and I think they were successful. Is there some sample code using SciSpark that I can run to make sure I've done everything right and get a better understanding of what's going on?

**Comment by valeriearoth** [comment]
Thank you so much for your help with this.

**Comment by sujen1412** [comment]
Sure no problem. 

Once you run sbt clean assembly, you could try running "org.dia.algorithms.mcc.MainNetcdfDFSMCC" with a spark-submit job. Optionally provide the required command line arguments. And check for VertexAndEdgeList.txt file to be created. If this works without any errors, you're set up is good to go.

**Comment by valeriearoth** [comment]
With and without command line arguments, it seems to be unable to parse the master URL. Do you know why that might be?

**Comment by valeriearoth** [comment]
Kim helped me to figure this out. Do we want to update the readme now?

**Comment by kwhitehall** [comment]
@valeriearoth  +1 to updating the readme.

**Comment by valeriearoth** [comment]
@kwhitehall Cool, thanks. I created a pull request (#42).
