### ISSUE TITLE
Add folder for wiki resources

### ISSUE THREAD

**Issue by sujen1412** [SciSpark/SciSpark#41]
We should have a folder where we all can work on a wiki. Once done, submit a pull request and then copy it on to the main repository wiki. 

In this way, we will be able to track changes and get notified by any updates that are made on the wiki.

**Comment by chrismattmann** [comment]
Sujen, just use: https://github.com/SciSpark/SciSpark/wiki

**Comment by kwhitehall** [comment]
Closing this as we have scisparkWiki repo as well.
