### ISSUE TITLE
Setting up gitter for SciSpark

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#5]
I have tried to set up a gitter chat room for SciSpark. However I cannot get access to the repo - possibly because it is private. Someone who has admin access to the repository should be able to do this.

http://gitter.im

**Comment by lewismc** [comment]
Who created the organization?

On Tue, Oct 13, 2015 at 11:08 AM, rahul palamuttam <notifications@github.com

> wrote:
> 
> I have tried to set up a gitter chat room for SciSpark. However I cannot
> get access to the repo - possibly because it is private. Someone who has
> admin access to the repository should be able to do this.
> 
> http://gitter.im
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SciSpark/SciSpark/issues/5.

## 

_Lewis_

**Comment by chrismattmann** [comment]
Better yet, we can have a Glip channel for this. @wmburke can you set this up?

**Comment by wmburke** [comment]
@chrismattmann Ok - I set this up and added you, Lewis, and Rahul to it. I believe any of you can add other people to it but let me know if you have any issues.

FYI: non-JPL employees should all be added as guests and not co-workers.

**Comment by chrismattmann** [comment]
thanks Wayne. @BrianWilson1 can you give a list of people to add to @wmburke ? should include:
- Mazi
- BrianW
- PaulR
- Kim
- Rahul
- Lewis
  ...more

**Comment by wmburke** [comment]
FYI: I added all of those listed above.

**Comment by chrismattmann** [comment]
thank you did you add @legendOfZelda ?

**Comment by wmburke** [comment]
Nope - and I can't without an email address.

**Comment by ghost** [comment]
my mail's now visible on my git account

**Comment by wmburke** [comment]
Great! Then you're added. You can hide your email again if you'd like. ;)

**Comment by ghost** [comment]
yep, thanks

**Comment by rahulpalamuttam** [comment]
@chrismattmann 
@MBoustani 
@BrianWilson1 

I remember in a previous meeting we decided to setup gitter for this repo.
I think only those who have admin rights can do this on the repo.

**Comment by rahulpalamuttam** [comment]
PR above has readme updated with gitter badge.
The community lobby room can be found here https://gitter.im/scientificspark/Lobby

For some reason gitter wouldn't allow me to name the community "scispark" so chose "scientificspark" instead.

**Comment by rahulpalamuttam** [comment]
closing the issue as we now have gitter.
