### ISSUE TITLE
Write netcdf file from data in sRDD

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#50]
In the typical workflow, once the scientist is satisfied with the computations on the dataset, they usually visualize using their custom scripts. As such it would be prudent to have a function to write the data in the sciTensors in the sRDD into files for that purpose. NetCDF is a commonly used format, there is the CF convention, and SciSpark can read netCDF files, hence it is proposed to develop a method to add to the codebase to facilitate such.

**Comment by kwhitehall** [comment]
This update partially hinders on the sciTensor restructuring. 

Nonetheless, it is proposed to create the function write_netcdf that accepts 5 dictionaries for parameters. These dictionaries are:
- varDataDict (needed)- a dictionary with the data and metaData data available for the variable. e.g. units, long_name etc. 
- timeDict (needed) - a dictionary with the time (as string) and metaData 
- globalDict - a dictionary with the sciTensor metaData e.g. the filepath the data was taken from originally
- latDict (optional) - a dictionary with the latitude array and associated metaData e.g. units, long_name
- lonDict (optional) - a dictionary with the longitude array and associated metaData e.g. units, long_name

Usage:
sRDD.map(p => {
write_netcdf(p("var").all, p("lat").all, p("lon").all, p("time"), p.metaData)
})

@chrismattmann  @BrianWilson1 @sujen1412 @rahulpalamuttam

**Comment by rahulpalamuttam** [comment]
@kwhitehall 
The above pull request 
deals with writing the SciDataset object to both the local filesystem.
It also includes additional functionality to write to HDFS.

This currently only works on RDD's of SciDatasets.
The original issue was filed for RDD's of SciTensors.

I'll file another PR for writing SciTensors to NetCDF Files.
Not entirely sure if we're going to continue developing SciTensor or completely move future efforts to SciDatasets (as SciTensor v2), so I'm implementing functionality for both.

**Comment by kwhitehall** [comment]
ok thanks @rahulpalamuttam.

**Comment by kwhitehall** [comment]
This issue has been addressed in PR #116
