### ISSUE TITLE
sRDD: partition by space / repartitioning (e.g. from time to space)

### ISSUE THREAD

**Issue by chrismattmann** [SciSpark/SciSpark#7]
Implement Partition by Space (or repartition from time to space) in 1st or 2nd Q 2016.

**Comment by rahulpalamuttam** [comment]
@chrismattmann @kwhitehall @BrianWilson1 

PR #141 addressed this.
Can the issue be closed?

**Comment by kwhitehall** [comment]
Yip @rahulpalamuttam! Thanks for the nudge :)
