### ISSUE TITLE
Reshape operation for SciTensor

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#72]
I've added this issue for the ESIP workshop, as I'm sure several users will be interested in reshaping their arrays. I'm seeing the need as I am attempting to replicate @agoodm succesful attempt at PDF clustering using the standard deviation and skewness. The netcdf file he has given me has a tasjan variable shaped (1023, 181, 286). I want to deal with the array with shape (33, 31, 181, 286).

The api call will look like this :
sciT("var").reshape(33, 31, 181, 286)

Here are a few questions/points I wanted to brainstorm on :
1. I originally thought it would be a good idea for AbstractTensor to also implement reshape. However Breeze only supports two dimensions. Nd4j on the otherhand. Nd4j on the otherhand does support reshaping. This is done by using the constructor and a new shape parameter.  
   Thus for now it makes sense to only provide the reshape function in SciTensor and not in the other tensor classes.
2. The reshape operation will be applied on the variable in use in the SciTensor. 
   Do we want the reshaped AbstractTensor to exist in another SciTensor, replace the corresponding AbstractTensor in the variable hashmap, or insert it as a new variable all together (the name is specified as an extra parameter by the user. 
   The api call will look like this:

sciT("var").reshape("reshapedVar", 33, 31, 181, 286)

@BrianWilson1 @kwhitehall thoughts?

**Comment by rahulpalamuttam** [comment]
Actually I see why reshape should be supported by the AbstractTensor, namely because classes Implementing AbstractTensor know what constructor to use - otherwise in SciTensor we need to do case statement type matching.

Also even though breeze supports only two dimensions - we can always do a shape changes like dimensions (100, 100) to (1000, 10).

Our BreezeTensor overall will be broken for the multidimensional case regardless because Breeze hasn't yet supported it.

I've updated the original issue

**Comment by kwhitehall** [comment]
Ack'ed @rahulpalamuttam. This is very useful functionality for sure beyond the use-case. 
Reiterating for my understanding, if you want to do inplace re-shaping in the tensor, the call is 
sciT("var").reshape(33, 31, 181, 286)
and if you want to make a copy of the reshaped var it is, 
sciT("var").reshape("reshapedVar", 33, 31, 181, 286)
Correct?
+1 for this functionality from me, and implementing it on the AbstractTensor and not the sciTensor.
Re the breeze implementation, if it is chosen for the backend implementation, I guess the code can throw an error msg & log towards the point of saying use ND4J backend for Abstract tensors for multiDim arrays. The documentation can reflect the same.

**Comment by rahulpalamuttam** [comment]
Thank you @kwhitehall 
I was actually indicating we add the reshape functionality to both the AbstractTensor and SciTensor.
SciTensor delegates to AbstractTensor.

I also want to point out that instead of having the individual shape parameters being passed to the function (through scala's varargs), we pass in a shape array. This is consistent with how numpy, matlab, and other array libraries do it. 

so the api will look like this :

sciT("var").reshape(Array(33, 31, 181, 286))
and
sciT("var").reshape("reshapedVar", Array(33,31,181,286))

**Comment by kwhitehall** [comment]
Agreed to passing the Array for the shape dims.

**Comment by rahulpalamuttam** [comment]
Shall we close this issue?

**Comment by kwhitehall** [comment]
Yip! Sry for the tardiness @rahulpalamuttam!
