### ISSUE TITLE
Add center coordinates to MCC node object

### ISSUE THREAD

**Issue by sujen1412** [SciSpark/SciSpark#74]
Following is the plan to find the center of a cloud element (MCC node)
1. Read the lat/lon information from the Netcdf files
2. Copy them into a two 1D arrays 
3. Find the corner points of a cloud element and compute the center.

**Comment by kwhitehall** [comment]
Hey @sujen1412, can you update on this?

**Comment by kwhitehall** [comment]
WIP code merged in PR #76
