### ISSUE TITLE
Implement Probability Density Function K-Means clustering from Loikith& Mattmann et al

### ISSUE THREAD

**Issue by chrismattmann** [SciSpark/SciSpark#8]
Implement the k-means clustering from this paper:

Loikith, P. C., et al. "Classifying reanalysis surface temperature probability density functions (PDFs) over North America with cluster analysis." Geophysical Research Letters 40.14 (2013): 3710-3714.

The paper is available here: http://research.atmos.ucla.edu/csi//REF/pdfs/LoikithEtal2013_revised.pdf

**Comment by ghost** [comment]
ok, im starting this

**Comment by ghost** [comment]
a basic implementation is done in #24

**Comment by chrismattmann** [comment]
Done in #24

**Comment by chrismattmann** [comment]
Description of algorithm here

![image](https://cloud.githubusercontent.com/assets/395887/12073237/2a5c6e18-b0c9-11e5-8887-3a07da9fa17d.png)
