### ISSUE TITLE
Removing nd4s depedency

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#95]
Nd4s is the scala wrapper library that gives us simple api calls for the more verbose nd4j functions.
After recently upgrading the nd4j version (which now does array allocations off-heap) the scala-style map/looping operations in nd4s no longer function as they should. They've also said that nd4s isn't exactly a top priority for them. 

The best course of action, I think, is to get rid of the dependency on nd4s.
We continue to support the normal api calls on AbstractTensor, but underneath we just have normal nd4j calls.

**Comment by BrianWilson1** [comment]
How did they screw nd4s up?
Why?

If they aren't responding to bugs, then using nd4j instead sounds good.

What conveniences do we lose?
Talk to you Monday.

Sent from my iPhone

On Aug 5, 2016, at 6:29 PM, rahul palamuttam <notifications@github.com<mailto:notifications@github.com>> wrote:

Nd4s is the scala wrapper library that gives us simple api calls for the more verbose nd4j functions.
After recently upgrading the nd4j version (which now does array allocations off-heap) the scala-style map/looping operations in nd4s no longer function as they should. They've also said that nd4s isn't exactly a top priority for them.

The best course of action, I think, is to get rid of the dependency on nd4s.
We continue to support the normal api calls on AbstractTensor, but underneath we just have normal nd4j calls.

**Comment by rahulpalamuttam** [comment]
It's not so much they screwed it up - but rather the new map functions don't exactly work now that they've gone off heap.

We lose getting to use +,-,\* - the operators and have to call subi, divi, addi, etc.

We also lose getting to use their nifty slicing syntax and instead use their more verbose indexing calls. ( we still keep our slicing syntax). 

This honesty is a non-issue (unless you see one). Our code didn't change much - and our users won't see a difference. I also like the idea of having our own scala api calls.

If we end up standardizing linear algebra api for scala :) - I'm happy with that.

**Comment by BrianWilson1** [comment]
Rahul,

So the off-heap map functions are broken?

Are they going to fix it?

I'm happy to do the scala side ourselves.

 -- Brian

**Comment by rahulpalamuttam** [comment]
I would rather do the scala side ourselves.
They use implicits to have scala syntax on their arrays.
I don't want to do something like:

import org.nds.Implicits._
Just to use the nd4s api.

They said they would fix it.
They also said they're bringing in c-forloops when/if we want to use loops.
Not exactly sure how that's going to be done or what they mean by that.

**Comment by rahulpalamuttam** [comment]
@BrianWilson1 
The PR is merged that addresses this.
I'm going to close the issue unless you want to discuss further.
Let me know.

**Comment by rahulpalamuttam** [comment]
closing this
