### ISSUE TITLE
Get rid of credentials in tests

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#96]
@chrismattmann 

I'm also not too happy about putting credentials in tests.
Are you completely against having credentials anywhere in the project?
I was thinking of having a file with the username/password on separate lines and reading that in our tests.

If not, lets find some other opendap datasets that don't rely on http authentication and use them instead.

**Comment by kwhitehall** [comment]
Addressed in PR #113.
