### ISSUE TITLE
Benchmarking tests

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#97]
Right now we have some performance tests alog with our unit tests [here](https://github.com/SciSpark/SciSpark/tree/master/src/test/scala/org/dia/tensors/perf)

We should have micro-benchmark tests for our individual function calls and some macro-benchmarks on our applications (MCC, pdfclustering etc.)

I was thinking of using [sbt-jmh](https://github.com/ktoso/sbt-jmh) for our benchmarking framework.

**Comment by rahulpalamuttam** [comment]
@chrismattmann @BrianWilson1 @kwhitehall 

[Here's the benchmark suite for scispark.](https://github.com/rahulpalamuttam/SciSparkPerf)
Perhaps we want to move it to the SciSpark organization?

It runs scale tests on the tensor classes and it's ops for different matrix sizes (elementwise, matrix-op, java-for-loop iteration).

It also runs tests on NetcdfDFSFile (reading from HDFS) and a run of MCC for different file sizes.

You can set it up by following the readme. 
Let me know if you have any issues with the setup.
It should be able to run as-is anyway.

I have some benchmarks running right now that have been configured to run on the cluster.

you can find the configuration for that under sdeploy at /rpalamut/SciSparkPerf

**Comment by kwhitehall** [comment]
@rahulpalamuttam transferred to this repo to the SciSpark team repo. @pzimdars This maybe of interest to you as well.

**Comment by rahulpalamuttam** [comment]
Addressed in #163.
